version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx1584m
      TERM: dumb
    steps:
      - checkout
      - restore_cache:
          keys:
          - jars-{{ checksum "build.gradle" }}
      - run:
        name: Build project
        command: ./gradlew build
      - save_cache:
          paths:
            - ~/.m2
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
      - run:
        name: Generate coverage for tests
        command: ./gradlew jacocoTestReport
      - run: 
        name: Upload generated coverage
        command: bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN
